export const SITE = {
  name: "Alliance Medical Center",
  tagline: "Compassionate Care. Healthier You.",
  phone: "248-607-0191",
  phoneHref: "tel:+12486070191",
  fax: "248-555-0147",
  email: "info@alliancemedicalcenter.example",
  address: {
    line1: "1220 N Perry St.",
    line2: "Pontiac, MI 48340",
    full: "1220 N Perry St., Pontiac, MI 48340",
    mapsHref: "https://www.google.com/maps/search/?api=1&query=1220+N+Perry+St.+Pontiac+MI+48340",
    directionsHref: "https://www.google.com/maps/dir/?api=1&destination=1220+N+Perry+St.+Pontiac+MI+48340",
  },
  mailtoHref: "mailto:info@alliancemedicalcenter.example",
  hours: {
    days: "Monday – Sunday",
    time: "12:00 PM – 8:00 PM",
    summary: "Open 7 Days · 12:00 PM – 8:00 PM",
  },
  bookingHref: "/book-appointment",
  contactHref: "/contact",
  urgentCareHref: "/urgent-care",
  occupationalHealthHref: "/occupational-health",
  diagnosticServicesHref: "/services/diagnostic-services",
  womensHealthHref: "/services/womens-health",
  pediatricCareHref: "/services/pediatric-care",
  familyHealthHref: "/services/family-health",
} as const;
