import type { ServiceItem } from "./Services.types";

export const SERVICES: ServiceItem[] = [
  {
    id: "urgent-care",
    title: "Urgent Care",
    description: "Same-day care for illnesses, minor injuries, and immediate medical needs.",
    icon: "medical-kit",
    accentColor: "#12899F",
    href: "#",
    animationDelayMs: 80,
  },
  {
    id: "family-health",
    title: "Family Health",
    description: "Ongoing primary and preventive care for children, adults, and families.",
    icon: "users",
    accentColor: "#12A673",
    href: "#",
    animationDelayMs: 130,
  },
  {
    id: "weight-loss",
    title: "Weight Loss",
    description: "Personalized support for healthy weight and long-term wellness goals.",
    icon: "heart-pulse",
    accentColor: "#0BA168",
    href: "#",
    animationDelayMs: 180,
  },
  {
    id: "occupational-health",
    title: "Occupational Health",
    description: "Workplace health services, physicals, testing, and employer care.",
    icon: "briefcase",
    accentColor: "#7546E8",
    href: "#",
    animationDelayMs: 230,
    titleNoWrap: true,
  },
  {
    id: "womens-health",
    title: "Women's Health",
    description: "Supportive preventive and everyday healthcare for women.",
    icon: "heart",
    accentColor: "#F13C6C",
    href: "#",
    animationDelayMs: 280,
  },
  {
    id: "pediatric-care",
    title: "Pediatric Care",
    description: "Convenient care for children and common childhood health concerns.",
    icon: "teddy-bear",
    accentColor: "#F29400",
    href: "#",
    animationDelayMs: 330,
  },
  {
    id: "diagnostic-services",
    title: "Diagnostic Services",
    description: "On-site labs, X-rays, testing, and diagnostic support.",
    icon: "flask",
    accentColor: "#6248E8",
    href: "#",
    animationDelayMs: 380,
  },
  {
    id: "education",
    title: "Education",
    description: "Helpful health information and resources for patients and families.",
    icon: "book-open",
    accentColor: "#0BA47A",
    href: "#",
    animationDelayMs: 430,
  },
];
